---
- name: Deploy app in new namespace
  hosts: webserver
  tasks:
    - name: Create namespace
      kubernetes.core.k8s:
        name: my-app
        api_version: v1
        kind: Namespace
        state: present
        kubeconfig: /root/.kube/config
    - name: Deploy nginx app
      kubernetes.core.k8s:
        src: nginx-config.yaml
        state: present
        kubeconfig: /root/.kube/config
        namespace: my-app