---
- name: Deploy app in new namespace
  hosts: all
  tasks:
    - name: Create a k8s namespace
      k8s:
        name: my-app
        api_version: v1
        kind: Namespace
        state: present
    - name: Deploy nginx app
      k8s:
        src: /home/joeri/Sites/devops/techworld-with-nana/Joeri-Abbo-techworld-with-nana-ansible/files/nginx-deployment.yaml
        state: present
        namespace: my-app