---
- name: Install Java and net-tools
  hosts: webserver
  tasks:
    - name: Update apt repo and cache
      become: yes
      apt:
        update_cache: yes
        cache_valid_time: 3600
        force_apt_get: yes
    - name: Install node and npm
      become: yes
      apt:
        pkg:
          - openjdk-8-jdk-headless
          - htop
          - net-tools

- name: Download and unpack Nexus installer
  hosts: webserver
  tasks:
    - name: Download nexus
      become: yes
      get_url:
        url: https://download.sonatype.com/nexus/3/latest-unix.tar.gz
        dest: /opt/
      register: nexus_download_result
    - name: Untar nexus installer
      become: yes
      unarchive:
        src: "{{ nexus_download_result.dest }}"
        dest: /opt/
        remote_src: yes
    - name: Find nexus folder
      find:
        paths: /opt
        patterns: nexus-*
        file_type: directory
      register: nexus_folder
    - name: Check if nexus folder already exists
      stat:
        path: /opt/nexus
      register: nexus_folder_exists
      ignore_errors: yes
    - name: Rename nexus folder
      become: yes
      shell: "mv {{ nexus_folder.files[0].path }} /opt/nexus"
      when: not nexus_folder_exists.stat.exists