---
- name: Configure nginx web server
  hosts: webserver
  tasks:
    - name: Upgrade all apt packages
      apt: upgrade=dist force_apt_get=yes
      become: yes
    - name: Install nginx server
      become: yes
      apt:
        name: nginx
        state: present
    - name: Start nginx server
      service:
        name: nginx
        state: started